import copy from './alfa-copy.json';
import {caseHeader,caseFooter} from './case-shell.js';
const t=id=>copy[id];
const text=(id,tag='p',cls='')=>`<${tag} class="${cls}" data-copy="${id}">${t(id)}</${tag}>`;
const img=(name,alt,cls='case-image')=>`<img class="${cls}" src="/assets/alfa/${name}.png" alt="${alt}" loading="lazy" decoding="async">`;
const notes=(ids,emoji='☝🏻',red=false)=>`<div class="alfa-notes ${red?'red':''}">${ids.map(id=>`<article><span aria-hidden="true">${emoji}</span>${text(id)}</article>`).join('')}</div>`;
const video=(id,title)=>`<div class="alfa-video"><video ${id==='999277633'?'src="/videos/alf-visualisation.mp4"':'data-src="/videos/alf-2.mp4"'} autoplay muted loop playsinline preload="metadata" disablepictureinpicture disableremoteplayback aria-label="${title}" poster="${id==='999277633'?'/assets/alfa-cover.png':'/assets/alfa/imgImage91.png'}"></video><button class="video-fallback" type="button">Включить видео</button></div>`;
const showcase=(id,title,steps,images)=>`<section class="showcase" id="${id}" aria-label="${t(title)}"><div class="showcase-sticky"><div class="showcase-copy"><div class="showcase-dots" aria-hidden="true">${steps.map((_,i)=>`<span class="${i===0?'active':''}"></span>`).join('')}</div>${text(title,'h2')}<div class="showcase-descriptions">${steps.map((step,i)=>`<div class="showcase-step ${i===0?'active':''}" aria-hidden="${i!==0}">${typeof step==='string'?text(step,'p','case-lead'):step.map(part=>text(part,'p','case-lead')).join('')}</div>`).join('')}</div></div><div class="showcase-screen">${images.map((name,i)=>`<div class="showcase-image ${i===0?'active':''}" aria-hidden="${i!==0}">${img(name,`${t(title)} — ${i+1}`,'')}</div>`).join('')}</div></div></section>`;
const more=[['111:4054','111:4055','imgPicture2','https://www.linkedin.com/feed/update/urn:li:activity:7478706770333384704/','LINKEDIN'],['111:4027','111:4028','imgPicture1','https://www.linkedin.com/feed/update/urn:li:activity:7480187042933477377/','LINKEDIN'],['111:4061','111:4062','imgPicture4','https://www.behance.net/gallery/235788613/redizajn-ii-assistenta-alfa-banka','BEHANCE']];
export const content=`<a class="skip" href="#case-content">Перейти к кейсу</a>${caseHeader.replace('</header>','<div class="language" aria-label="Язык / Language"><button type="button" data-lang="ru" aria-pressed="true">RU</button><span>/</span><button type="button" data-lang="en" aria-pressed="false">ENG</button></div></header>')}<main id="case-content" class="case-main alfa-main">
<section class="case-intro">${text('26:10373','h1')}${text('26:10374','p','case-lead')}<dl class="case-meta"><div><dt>Роль</dt><dd>Product designer</dd></div><div><dt>Процесс</dt><dd>Research • Visual Design • UX/UI • Prototyping • AI Interaction Design • Product Vision</dd></div><div><dt>Команда</dt><dd><a href="https://amgeldorje.com/" target="_blank" rel="noopener noreferrer">Амгалан Доржиев, designer ↗</a></dd></div><div><dt>Дата</dt><dd>Август 2025</dd></div></dl>${video('999277633','ALF 2.0 — концепция ассистента')}</section>
<section>${notes(['111:8716','111:8719','111:8722'],'🎯')}</section>
<section>${text('109:1031','h2','alfa-subheading')}${img('imgImage54','Интерфейс Альф 1.0 из 2021 года')}</section>
<section class="alfa-research">${notes(['109:955','109:958','109:961','109:1017','109:1021'],'❌',true)}<aside class="research-methods"><ul><li>Оценила удобство использования существующего интерфейса и сформулировала гипотезы для проверки с пользователями.</li><li>Провела пять коридорных тестов с клиентами Альфа-Банка, чтобы понять их самые частые запросы к голосовому помощнику.</li></ul></aside></section>
<section>${img('imgImage55','Исследование сценариев и аналогичных AI-ассистентов')}</section>
<section class="alfa-research">${notes(['109:1126','109:1129','109:1132','109:1135'])}<aside class="research-methods"><p>Интервью с 10 клиентами банка, чтобы выяснить:</p><ul><li>как они планируют бюджеты,</li><li>с какими сложностями сталкиваются в управлении финансами,</li><li>как относятся к внедрению AI в приложение банка.</li></ul></aside></section>
<section class="alfa-insight">${text('109:1122','p','case-lead')}</section>
<section class="alfa-insight">${text('111:1141','h2')}</section>
${showcase('financial-adviser','111:1723',['111:1725','111:4379','111:4393'],['imgImage91','imgImage92','imgImage93'])}
<section class="alfa-gallery" aria-label="Сценарии финансового ассистента">${['imgImage78','imgImage81','imgImage82','imgImage83','imgImage83','imgImage93','imgImage83','imgImage85'].map((name,i)=>img(name,`Экран ассистента ${i+1}`,'')).join('')}</section>
${showcase('bank-consultant','111:1730',['consultant-intro','111:4407','111:4418'],['imgImage94','imgImage95','imgImage96'])}
<section>${text('111:3879','h2')}${video('999273365','ALF 2.0 — голосовое взаимодействие')}</section>
<section>${text('279:6418','h2')}<div class="case-lead alfa-result-copy"><p>Проект стал победителем конкурса по редизайну AI-ассистента Альфа-Банка.</p><p>Главный результат проекта — смена модели взаимодействия между пользователем и финансовым продуктом от транзакционного интерфейса к интеллектуальному финансовому сопровождению.</p></div><div class="case-results alfa-results">${[['324:43971','324:43972'],['324:43974','324:43975'],['324:43977','324:43978'],['324:43980','324:43981']].map(([heading,desc])=>`<div>${text(heading,'h3')}${text(desc)}</div>`).join('')}</div></section>
<section>${text('111:3921','h2','alfa-subheading')}${notes(['111:3927','111:3930','111:3933','111:3936'])}</section>
<section class="alfa-more">${text('111:4012','h2')}<div class="alfa-articles">${more.map(([title,desc,picture,url,label])=>`<a class="alfa-article" href="${url}" target="_blank" rel="noopener noreferrer"><div class="alfa-article-copy">${text(title,'h3')}${text(desc)}</div><div class="alfa-article-image">${img(picture,'','')}<span>${label} ↗</span></div></a>`).join('')}</div></section>
</main>${caseFooter}`;
