import {initCaseShowcases} from './case-showcase.js';
import './smooth-scroll.js';
import '@fontsource-variable/geist';
import '@fontsource-variable/geist-mono';
import './style.css';
import './nspk.css';
import './alfa.css';
import {mountCase} from './page-language.js';
import {initCaseVideos} from './case-videos.js';
import {initCaseMenu} from './case-menu.js';
mountCase();
initCaseMenu();
initCaseVideos();
initCaseShowcases();
