import {caseHeader,caseFooter} from "./case-shell.js";
const asset=name=>`/assets/nspk/${name}`;
const image=(name,alt,cls='case-image')=>`<img class="${cls}" src="${asset(name)}" alt="${alt}" loading="lazy" decoding="async">`;
const compare=(id,before,after,label)=>`<figure class="comparison" id="${id}" style="--reveal:50%" aria-label="${label}"><img src="${asset(after)}" alt="После: ${label}" loading="lazy" draggable="false"><img class="comparison-before" src="${asset(before)}" alt="До: ${label}" loading="lazy" draggable="false"><span class="compare-label before">До</span><span class="compare-label after">После</span><span class="compare-divider" aria-hidden="true"><span>‹ ›</span></span><input type="range" min="0" max="100" value="50" aria-label="${label}: положение шторки" aria-valuetext="До 50%, после 50%"></figure>`;
export const content=`
<a class="skip" href="#case-content">Перейти к кейсу</a>
${caseHeader}
<main class="case-main" id="case-content">
<section class="case-intro"><h1>Аудит национальной платежной системы</h1><div class="case-lead"><p>НСПК — это B2B-платформа, которая обрабатывает заявки от банков на выпуск карт «МИР».</p><p>Я провела UX-аудит, выявила проблемные зоны, которые мешают легко подключать новые банки, и предложила улучшения через редизайн ключевых сценариев.</p></div><dl class="case-meta"><div><dt>Роль</dt><dd>Продуктовый дизайнер</dd></div><div><dt>Процесс</dt><dd>Research • UX/UI • Prototyping • Product Vision</dd></div><div><dt>Team</dt><dd>Мария Штейн, Project Lead</dd></div><div><dt>Date</dt><dd>2025</dd></div></dl><div class="case-cover">${image('hero.png','Обновлённая платформа НСПК — список профилей','case-cover-image')}</div></section>
<section class="case-context"><p>Компания планировала масштабировать систему и подключать больше банков и пользователей. При этом высокий порог входа в работу с системой требовал личного обучения новых сотрудников опытными коллегами.</p><p>Это делало рост платформы дорогим и критически зависимым от человеческого фактора.</p></section>
<section class="carousel" aria-label="Slider 1 — исходный интерфейс НСПК" aria-roledescription="карусель"><div class="carousel-viewport" tabindex="0" aria-label="Слайды интерфейса; стрелки влево и вправо переключают слайды"><div class="carousel-track">${['112-3936-imgImage261.png','112-3936-imgImage262.png','112-3936-imgImage263.png'].map((name,i)=>`<div class="carousel-slide" role="group" aria-roledescription="слайд" aria-label="${i+1} из 3">${image(name,['Экран входа в платформу','Список профилей до редизайна','Информация о карте до редизайна'][i])}</div>`).join('')}</div></div><div class="carousel-controls"><button class="carousel-prev" aria-label="Предыдущий слайд">‹</button><div class="carousel-dots">${[0,1,2].map(i=>`<button data-slide="${i}" aria-label="Слайд ${i+1}" aria-pressed="${i===0}"></button>`).join('')}</div><button class="carousel-next" aria-label="Следующий слайд">›</button></div><p class="sr-only carousel-status" aria-live="polite"></p></section>
<section><h2>Бизнес-цели</h2><div class="business-goals"><article><h3>${image('111-8727-imgTime.svg','','goal-icon')}Уменьшить TTV</h3><p>Ускорить онбординг новых сотрудников банков</p></article><article><h3>${image('111-8727-imgWarning.svg','','goal-icon')}Снизить Operational Costs</h3><p>Уменьшить количество обращений в поддержку</p></article><article><h3>${image('111-8727-imgComponent.svg','','goal-icon')}Унифицировать систему</h3><p>Привести компоненты к единому стандарту</p></article></div></section>
<section><h2>Исследования</h2><p class="case-lead research-lead">Выявленные проблемы были не отдельными недостатками интерфейса: они проявили глубинное несоответствие между сложностью системы и возможностями пользователей.</p><div class="research-grid"><div class="findings"><article><span aria-hidden="true">❌</span><div><h3>Система структурно зрелая, но когнитивно перегруженная</h3><p>Система выглядела аккуратно и логично, но в ней было много полей, настроек и терминов, почти не было подсказок, ошибки объяснялись слабо.</p><p>Новым пользователям было трудно понять, что от них ждут и в каком порядке действовать.</p></div></article><article><span aria-hidden="true">❌</span><div><h3>Функциональность не адаптирована под уровень подготовки пользователя</h3><p>Один и тот же интерфейс предлагал одинаковый набор действий и настроек всем пользователям — и новичкам, и опытным специалистам. Система не помогала постепенно освоиться и перейти от простых задач к более сложным.</p></div></article><article><span aria-hidden="true">❌</span><div><h3>Отсутствует визуальная приоритизация и поддержка принятия решений</h3><p>Пользователю приходилось самому разбираться, какие поля обязательные, какие действия важнее и на каком этапе он находится, из-за чего возрастал риск ошибок и замедлялась работа.</p></div></article></div><aside class="research-methods"><ul><li>Тестирование System Usability Scale для оценки удобства интерфейса</li><li>Оценка пользовательских сценариев по эвристикам Нильсена</li><li>Проработка решений через редизайн ключевых сценариев</li><li>Тестирование сценариев на контрольной группе</li></ul></aside></div></section>
<section><h2>Принцип Progressive Disclosure</h2><p class="case-lead solution-lead">Я разделила сценарии на базовые и расширенные. Базовый сценарий фокусирует на обязательных полях для быстрого старта, а расширенный даёт полный контроль опытным пользователям.</p>${image('111-8727-imgImage56.png','Базовый и расширенный сценарии создания профиля')}</section>
<section><h2>Переработка дизайн-системы</h2><p class="case-lead solution-lead">Я провела ревизию всех компонентов, удалила лишние сущности и создала унифицированные паттерны для фильтров, таблиц и форм.</p>${compare('comparison-1','112-4124-imgImage264.png','112-4124-imgImage265.png','Дизайн-система: список профилей')}</section>
<section><h2>Контекстное обучение</h2><div class="case-lead solution-lead"><p>Инструкции были оформлены отдельным документом, вынуждая постоянно обращаться к файлам и тратить время на загрузку и поиск нужной информации.</p><p>Я исправила это и интегрировала базы знаний в интерфейс.</p></div>${compare('comparison-2','112-4163-imgImage266.png','112-4163-imgImage72.png','Контекстное обучение: валидация')}</section>
<section><h2>Встроенная поддержка принятия решений</h2><p class="case-lead solution-lead">Внедрила Contextual Help и визуальное выделение рекомендованных значений.</p>${image('111-8727-imgImage59.png','Контекстные подсказки и рекомендованные значения в форме')}</section>
<section><h2>Результаты</h2><div class="case-lead"><p>Команда НСПК внедрила улучшения по 15+ ключевым сценариям, убирая ограничения для роста платформы.</p><p>Продукт получил фундамент для быстрого онбординга новых банков-партнёров, снизил нагрузку на отдел поддержки и уменьшил количество брака при выпуске карт.</p></div></section>
<section class="case-results" aria-label="Результаты в цифрах"><div><h3>−32%<br>ошибок</h3><p>Допускаемых при первом прохождении сценариев новыми пользователями</p></div><div><h3>Support<br>Load ↓</h3><p>Меньше обращений в поддержку благодаря понятному интерфейсу</p></div><div><h3>Time to<br>Success ↓</h3><p>Новые пользователи успешно завершали задачи без помощи извне</p></div></section>
<section class="next-case-section"><h2>Следующий кейс</h2><a class="next-case" href="/?case=vtb"><img class="next-case-image" src="${asset('111-8727-imgImage.png')}" alt="" loading="lazy"><span class="next-case-copy"><span class="case-tag">FINTECH</span><span class="next-case-title">Личный кабинет клиента ВТБ НПФ</span></span><span class="next-arrow">${image('111-8727-imgArrowForward.svg','')}</span></a></section>
</main>
${caseFooter}`;
