import copy from './vtb-copy.json';
import {caseHeader,caseFooter} from './case-shell.js';
const text=(id,tag='p',cls='')=>`<${tag} class="${cls}">${copy[id]}</${tag}>`;
const paragraphs=(id,cls='case-lead')=>`<div class="${cls}">${copy[id].split('\n\n').map(p=>`<p>${p}</p>`).join('')}</div>`;
const image=(name,alt,cls='case-image',ext='png')=>`<img class="${cls}" src="/assets/vtb/${name}.${ext}" alt="${alt}" loading="lazy" decoding="async">`;
const showcase=(id,title,description,details,images)=>`<section class="showcase" id="${id}" aria-label="${copy[title]}"><div class="showcase-sticky"><div class="showcase-copy"><div class="showcase-dots" aria-hidden="true"><span class="active"></span><span></span></div>${text(title,'h2')}${text(description,'p','showcase-intro')}<div class="showcase-descriptions">${details.map((detail,i)=>`<div class="showcase-step ${i===0?'active':''}" aria-hidden="${i!==0}">${text(detail,'p','case-lead')}</div>`).join('')}</div></div><div class="showcase-screen">${images.map((name,i)=>`<div class="showcase-image ${i===0?'active':''}" aria-hidden="${i!==0}">${image(name,`${copy[title]} — ${i+1}`,'')}</div>`).join('')}</div></div></section>`;
export const content=`<a class="skip" href="#case-content">Перейти к кейсу</a>${caseHeader.replace('</header>','<div class="language" aria-label="Язык / Language"><button type="button" data-lang="ru" aria-pressed="true">RU</button><span>/</span><button type="button" data-lang="en" aria-pressed="false">ENG</button></div></header>')}
<main class="case-main vtb-main" id="case-content">
<section class="case-intro">${text('113:4752','h1')}${paragraphs('113:4753')}<dl class="case-meta"><div><dt>Роль</dt><dd>Product designer</dd></div><div><dt>Процесс</dt><dd>Research • UX/UI • Prototyping • Product Vision • Testing</dd></div><div><dt>Команда</dt><dd><span>Роман Беньо, арт-директор</span><br><a href="https://edgor.fixframer.ru/" target="_blank" rel="noopener noreferrer"><span>Эдуард Горбунов, Senior Product Designer</span> ↗</a></dd></div><div><dt>Дата</dt><dd>2025–2026</dd></div></dl><div class="vtb-cover">${image('hero','Личный кабинет ВТБ НПФ — новый интерфейс')}</div></section>
<section>${paragraphs('113:7147','case-context')}</section>
<section class="carousel vtb-carousel" aria-label="Интерфейс до редизайна" aria-roledescription="карусель"><div class="carousel-viewport" tabindex="0" aria-label="Слайды интерфейса; стрелки влево и вправо переключают слайды"><div class="carousel-track">${['slider-imgImage54','slider-imgImage56','slider-imgImage55'].map((name,i)=>`<div class="carousel-slide" role="group" aria-label="${i+1} из 3">${image(name,['Вход в личный кабинет','Информация по счёту','Программа долгосрочных сбережений'][i])}</div>`).join('')}</div></div><div class="carousel-controls"><button class="carousel-prev" aria-label="Предыдущий слайд">‹</button><div class="carousel-dots">${[0,1,2].map(i=>`<button data-slide="${i}" aria-label="Слайд ${i+1}" aria-pressed="${i===0}"></button>`).join('')}</div><button class="carousel-next" aria-label="Следующий слайд">›</button></div><p class="sr-only carousel-status" aria-live="polite"></p></section>
<section>${paragraphs('237:1395','case-context')}</section>
<section>${text('237:1373','h2')}${text('238:3644','p','case-lead solution-lead')}<div class="business-goals">${[['imgWallet','237:1378','237:1379'],['imgStats','237:1383','237:1384'],['imgComponent','237:1388','237:1389']].map(([icon,title,desc])=>`<article><h3>${image(icon,'','goal-icon','svg')}${copy[title]}</h3>${text(desc)}</article>`).join('')}</div></section>
<section class="vtb-research">${text('237:1398','h2')}${image('imgImage97','Результаты UX-аудита и направления редизайна')}${paragraphs('248:13692','case-context')}<div class="research-grid"><div class="findings">${[['237:1404','237:1405'],['237:1414','237:1415'],['237:1409','237:1410'],['238:3649','238:3650']].map(([title,desc])=>`<article><span aria-hidden="true">❌</span><div>${text(title,'h3')}${paragraphs(desc,'')}</div></article>`).join('')}</div><aside class="research-methods"><ul>${copy['237:1417'].split('\n\n').map(p=>`<li>${p}</li>`).join('')}</ul></aside></div></section>
<section>${paragraphs('237:1425','vtb-role')}</section>
${showcase('savings-model','113:4837','113:4838',['237:1432','237:3553'],['imgImage91','imgImage92'])}
${showcase('savings-goals','113:4873','113:4874',['238:3565','238:3573'],['imgImage93','imgImage94'])}
${showcase('contextual-actions','238:3601','238:3602',['238:3603','238:3593'],['imgImage95','imgImage96'])}
<section class="alfa-gallery" aria-label="Экраны личного кабинета">${['imgImage78','imgImage81','imgImage82','imgImage83','imgImage86','imgImage87','imgImage88','imgImage85'].map((name,i)=>image(name,`Экран личного кабинета ${i+1}`,'')).join('')}</section>
<section>${text('238:3614','h2')}${paragraphs('238:3615')}</section>
<section class="case-results">${[['238:3619','238:3620'],['238:3622','238:3623'],['238:3625','238:3626']].map(([title,desc])=>`<div>${text(title,'h3')}${text(desc)}</div>`).join('')}</section>
<section>${text('238:3652','p','vtb-thanks')}</section>
<section class="next-case-section">${text('238:3628','h2')}<a class="next-case vtb-next" href="/cases/alfa/"><div class="vtb-next-art">${image('next-alfa','','')}</div><span class="next-case-copy"><span class="case-tag">FINTECH</span><span class="next-case-title">${copy['238:3633']}</span></span><span class="next-arrow">${image('imgArrowForward','','','svg')}</span></a></section>
</main>${caseFooter}`;
