import './alfa.css';
import './vtb.css';
import './smooth-scroll.js';
import {mountCase} from './page-language.js';
import {initCaseMenu} from './case-menu.js';
import {initCaseShowcases} from './case-showcase.js';
import {initCaseCarousel} from './case-carousel.js';
mountCase();
initCaseMenu();
initCaseShowcases();
initCaseCarousel(document.querySelector('.carousel'));
